version: '4.5'
services:
  # GITLAB
  gitlab-web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-web
    hostname: 'my-gl.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://my-gl.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '81:80'
      - '444:443'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network

  # RUNNER
  # gitlab-runner1:
  #   image: gitlab/gitlab-runner:alpine
  #   restart: always
  #   container_name: gitlab-runner1
  #   hostname: gitlab-runner1
  #   depends_on:
  #     - gitlab-web
  #   volumes:
  #     - ./config/gitlab-runner:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - gitlab-network
# kdH2L6mgBdZ+kaY09pGQEkQf3VeZpM296RwI6bYfOxo=
networks:
  gitlab-network:
    name: gitlab-network
